name: Test Reuse

on:
  workflow_dispatch:

jobs:
  reusefail:
    name: Test reusable call
    uses: sdr-enthusiasts/common-github-workflows/.github/workflows/sdre.yml@4cf063e5906338b3b92f0fe71d8dbae52c180d99
    with:
      push_enabled: false
      ghcr_repo_owner: zulufoxtrot
      ghcr_repo: zulufoxtrot/docker-adsb-ultrafeeder
      docker_build_file: Dockerfile
      platform_linux_arm32v7_enabled: false
      platform_linux_arm64v8_enabled: false
      verify_s6_enabled: false
    secrets:
      ghcr_token: ${{ secrets.GITHUB_TOKEN }}
